# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: N M Sheldon
email: 106749884+nms-scribe@users.noreply.github.com
description: Blogging about role-playing games, worldbuilding, maps and writing
baseurl: "" # the subpath of your site, e.g. /blog
github_username:  nms-scribe
excerpt_separator: <!--more-->


# Build settings
#theme: jekyll-theme-dinky
plugins:
  - jekyll-feed

# I dislike the default organization of the posts into category folders. It makes it really difficult to guess a URL.
permalink: /posts/:year-:month-:day-:title:output_ext

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude: # I have to include all of the defaults here just to add one directory (_tools) to the list... why!!?!?!?!?!!
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _tools/
  - test/
  - _drafts/*.published
  - _drafts/*.png # I put images in the drafts folder before publishing
  - readme.md
  
